#!/usr/bin/env bash
# setup_systemd.sh — One-shot installer for the polymarket-weather bot
# as a systemd service.  Auto-detects user, repo path, venv path, and
# generates a unit file from the template at deploy/weather_bot.service.
#
# Usage (run on the VPS):
#     cd ~/apps/polymarket-weather
#     sudo bash deploy/setup_systemd.sh
#
# Optional env-var overrides:
#     SERVICE_NAME=weather_bot   # systemd unit name (default)
#     RUN_USER=ubuntu            # user the service runs as (default: invoking user)
#     REPO_ROOT=/path/to/repo    # repo root (default: detected from script dir)
#     VENV_PYTHON=/path/python   # venv python path (default: detected)
#     ENV_FILE=/path/.env        # env file (default: $REPO_ROOT/.env if exists)
#     MEMORY_MAX=512M            # systemd MemoryMax (default: 512M)
#
# All predictor tuning (PREDICTOR_MODE, _FLAT_STAKE_USD, _MIN_EDGE, …)
# lives in .env — see the "Intraday Predictor" section there.
#
# What it does:
#   1. Detects paths
#   2. Stops the service if already running (safe to re-run)
#   3. Writes /etc/systemd/system/${SERVICE_NAME}.service
#   4. systemctl daemon-reload, enable, start
#   5. Prints status + how to tail logs
#
# Re-running is idempotent — it'll stop, rewrite, restart cleanly.

set -euo pipefail

# ----- Resolve identity (must be root) -------------------------------
if [[ $EUID -ne 0 ]]; then
    echo "ERROR: must be run with sudo (need to write /etc/systemd/system)" >&2
    echo "  sudo bash $0" >&2
    exit 1
fi

# ----- Auto-detect paths ---------------------------------------------
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DEFAULT_REPO_ROOT="$( cd "${SCRIPT_DIR}/.." && pwd )"
REPO_ROOT="${REPO_ROOT:-${DEFAULT_REPO_ROOT}}"

# RUN_USER: prefer SUDO_USER (the human who invoked sudo) over root
RUN_USER="${RUN_USER:-${SUDO_USER:-$(whoami)}}"
RUN_GROUP="$(id -gn "${RUN_USER}")"

SERVICE_NAME="${SERVICE_NAME:-weather_bot}"
MEMORY_MAX="${MEMORY_MAX:-512M}"

# Find venv python — try repo/venv first, then common alternatives
if [[ -z "${VENV_PYTHON:-}" ]]; then
    for candidate in \
        "${REPO_ROOT}/venv/bin/python" \
        "${REPO_ROOT}/.venv/bin/python" \
        "${REPO_ROOT}/env/bin/python"; do
        if [[ -x "${candidate}" ]]; then
            VENV_PYTHON="${candidate}"
            break
        fi
    done
fi
if [[ -z "${VENV_PYTHON:-}" || ! -x "${VENV_PYTHON}" ]]; then
    echo "ERROR: could not find venv python at ${REPO_ROOT}/venv/bin/python" >&2
    echo "       Pass VENV_PYTHON=/path/to/python explicitly, or create the venv first:" >&2
    echo "         cd ${REPO_ROOT} && python3 -m venv venv && venv/bin/pip install -r bot/requirements.txt" >&2
    exit 1
fi

# Env file — only set if it exists
ENV_FILE="${ENV_FILE:-${REPO_ROOT}/.env}"
ENV_FILE_DIRECTIVE=""
if [[ -f "${ENV_FILE}" ]]; then
    ENV_FILE_DIRECTIVE="EnvironmentFile=${ENV_FILE}"
else
    echo "NOTE: no .env file at ${ENV_FILE} — service will run without one."
    echo "      If you need POLYMARKET_PRIVATE_KEY etc., create it before going live."
fi

# bot/ subdir
WORK_DIR="${REPO_ROOT}/bot"
if [[ ! -d "${WORK_DIR}" ]]; then
    echo "ERROR: expected ${WORK_DIR} to exist" >&2
    exit 1
fi
if [[ ! -f "${WORK_DIR}/main.py" ]]; then
    echo "ERROR: expected ${WORK_DIR}/main.py to exist" >&2
    exit 1
fi

# ----- Show resolved config + confirm --------------------------------
UNIT_PATH="/etc/systemd/system/${SERVICE_NAME}.service"

echo "=== systemd installer ==="
echo "  service name:   ${SERVICE_NAME}"
echo "  unit path:      ${UNIT_PATH}"
echo "  run user/group: ${RUN_USER}/${RUN_GROUP}"
echo "  working dir:    ${WORK_DIR}"
echo "  venv python:    ${VENV_PYTHON}"
echo "  env file:       ${ENV_FILE} $( [[ -f ${ENV_FILE} ]] && echo '(found — all PREDICTOR_* settings come from here)' || echo '(MISSING — service will start without it)' )"
echo "  MemoryMax:      ${MEMORY_MAX}"
echo ""

# ----- Stop existing service if running ------------------------------
if systemctl is-active --quiet "${SERVICE_NAME}" 2>/dev/null; then
    echo "Stopping existing ${SERVICE_NAME} service…"
    systemctl stop "${SERVICE_NAME}"
fi

# ----- Generate unit file --------------------------------------------
echo "Writing ${UNIT_PATH} …"
cat > "${UNIT_PATH}" <<EOF
# Auto-generated by deploy/setup_systemd.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Re-run that script to update.

[Unit]
Description=Polymarket Weather Arbitrage Bot (with intraday predictor)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=${WORK_DIR}
ExecStart=${VENV_PYTHON} main.py
User=${RUN_USER}
Group=${RUN_GROUP}

${ENV_FILE_DIRECTIVE}

# All predictor tunables (PREDICTOR_MODE, _FLAT_STAKE_USD, _MIN_EDGE, …)
# come from .env so you can change them without re-running this installer.
# After editing .env: sudo systemctl restart ${SERVICE_NAME}

# Restart on crash; do not restart on clean shutdown.
Restart=on-failure
RestartSec=30s

# Give the bot 60s to shut down cleanly before SIGKILL.
TimeoutStopSec=60

# Log to journal (readable via journalctl -u ${SERVICE_NAME} -f).
StandardOutput=journal
StandardError=journal
SyslogIdentifier=${SERVICE_NAME}

# Resource ceiling — prevent runaway memory use.
MemoryMax=${MEMORY_MAX}

[Install]
WantedBy=multi-user.target
EOF

chmod 644 "${UNIT_PATH}"

# ----- Reload + enable + start ---------------------------------------
echo "systemctl daemon-reload …"
systemctl daemon-reload

echo "systemctl enable ${SERVICE_NAME} (start on boot)…"
systemctl enable "${SERVICE_NAME}"

echo "systemctl start ${SERVICE_NAME} …"
systemctl start "${SERVICE_NAME}"

# Give it a moment to start before showing status
sleep 2

# ----- Status + tips -------------------------------------------------
echo ""
echo "=== Service status ==="
systemctl status "${SERVICE_NAME}" --no-pager -l || true

echo ""
echo "=== Done ==="
echo "  Tail logs:    sudo journalctl -u ${SERVICE_NAME} -f"
echo "  Restart:      sudo systemctl restart ${SERVICE_NAME}"
echo "  Stop:         sudo systemctl stop ${SERVICE_NAME}"
echo "  Edit unit:    sudo nano ${UNIT_PATH} && sudo systemctl daemon-reload && sudo systemctl restart ${SERVICE_NAME}"
echo "  Disable boot: sudo systemctl disable ${SERVICE_NAME}"
echo ""
echo "  Confirm the intraday predictor registered:"
echo "    sudo journalctl -u ${SERVICE_NAME} | grep -i 'intraday_predictor'"