#!/usr/bin/env bash
# setup_dashboard_systemd.sh — Install the predictor dashboard as a
# managed systemd service.  The dashboard binds to 0.0.0.0 on
# DASHBOARD_PORT (from .env, default 8082), so it's reachable from any
# Tailscale-connected device at:
#
#     http://<vps-tailscale-ip>:<DASHBOARD_PORT>/predictor_dashboard.html
#
# No tmux, no SSH tunnel, no manual commands.  Service auto-starts on
# boot, auto-restarts on crash.
#
# Usage:
#     cd ~/apps/polymarket-weather
#     sudo bash deploy/setup_dashboard_systemd.sh
#
# Optional env-var overrides:
#     SERVICE_NAME=weather_dashboard    # systemd unit name (default)
#     RUN_USER=ubuntu                   # user the service runs as
#     REPO_ROOT=/path/to/repo           # repo root (default: detected)
#     VENV_PYTHON=/path/python          # venv python (default: detected)
#     ENV_FILE=/path/.env               # env file (default: $REPO_ROOT/.env)
#
# After install, tune dashboard behavior by editing .env:
#     DASHBOARD_PORT, DASHBOARD_WATCH_SEC, DASHBOARD_DAYS
# Then: sudo systemctl restart weather_dashboard

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: must be run with sudo." >&2
    echo "  sudo bash $0" >&2
    exit 1
fi

# ----- Path detection -----
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DEFAULT_REPO_ROOT="$( cd "${SCRIPT_DIR}/.." && pwd )"
REPO_ROOT="${REPO_ROOT:-${DEFAULT_REPO_ROOT}}"
RUN_USER="${RUN_USER:-${SUDO_USER:-$(whoami)}}"
RUN_GROUP="$(id -gn "${RUN_USER}")"
SERVICE_NAME="${SERVICE_NAME:-weather_dashboard}"

if [[ -z "${VENV_PYTHON:-}" ]]; then
    for cand in "${REPO_ROOT}/venv/bin/python" \
                 "${REPO_ROOT}/.venv/bin/python" \
                 "${REPO_ROOT}/env/bin/python"; do
        [[ -x "${cand}" ]] && VENV_PYTHON="${cand}" && break
    done
fi
if [[ -z "${VENV_PYTHON:-}" || ! -x "${VENV_PYTHON}" ]]; then
    echo "ERROR: could not find venv python in ${REPO_ROOT}." >&2
    echo "  Pass VENV_PYTHON=/path/to/python explicitly." >&2
    exit 1
fi

ENV_FILE="${ENV_FILE:-${REPO_ROOT}/.env}"
# NOTE: we deliberately do NOT use systemd's EnvironmentFile= for the
# dashboard.  Some systemd versions don't strip inline comments in .env
# files, which corrupts values like 'MAX_OPEN_POSITIONS=0  # cap'.
# The Python script calls load_dotenv() itself (which strips comments
# correctly) so .env values still get loaded — just via Python, not systemd.

WORK_DIR="${REPO_ROOT}/bot"
if [[ ! -f "${WORK_DIR}/scripts/predictor_dashboard.py" ]]; then
    echo "ERROR: ${WORK_DIR}/scripts/predictor_dashboard.py not found." >&2
    exit 1
fi

UNIT_PATH="/etc/systemd/system/${SERVICE_NAME}.service"
TAILSCALE_IP=""
if command -v tailscale &>/dev/null; then
    TAILSCALE_IP="$(tailscale ip -4 2>/dev/null | head -1 || true)"
fi

# Read DASHBOARD_PORT from .env if present (for nice access-URL printout)
DASH_PORT="8082"
if [[ -f "${ENV_FILE}" ]]; then
    DASH_PORT="$(grep -E '^DASHBOARD_PORT=' "${ENV_FILE}" 2>/dev/null | cut -d= -f2 | tr -d ' ' || echo 8082)"
    DASH_PORT="${DASH_PORT:-8082}"
fi

echo "=== systemd dashboard installer ==="
echo "  service name:   ${SERVICE_NAME}"
echo "  unit path:      ${UNIT_PATH}"
echo "  run user/group: ${RUN_USER}/${RUN_GROUP}"
echo "  working dir:    ${WORK_DIR}"
echo "  venv python:    ${VENV_PYTHON}"
echo "  env file:       ${ENV_FILE} $( [[ -f ${ENV_FILE} ]] && echo '(loaded by Python, not systemd)' || echo '(missing)' )"
echo "  dashboard port: ${DASH_PORT}"
[[ -n "${TAILSCALE_IP}" ]] && echo "  tailscale IP:   ${TAILSCALE_IP}"
echo ""

if systemctl is-active --quiet "${SERVICE_NAME}" 2>/dev/null; then
    echo "Stopping existing ${SERVICE_NAME} service…"
    systemctl stop "${SERVICE_NAME}"
fi

echo "Writing ${UNIT_PATH} …"
cat > "${UNIT_PATH}" <<EOF
# Auto-generated by deploy/setup_dashboard_systemd.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Re-run that script to update.

[Unit]
Description=Polymarket Weather Predictor Dashboard
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=${WORK_DIR}
ExecStart=${VENV_PYTHON} -m scripts.predictor_dashboard
User=${RUN_USER}
Group=${RUN_GROUP}

# All settings come from .env (DASHBOARD_PORT, DASHBOARD_WATCH_SEC,
# DASHBOARD_DAYS).  The script loads .env via python-dotenv itself
# (NOT via systemd's EnvironmentFile=) to avoid inline-comment parsing
# bugs in some systemd versions.  Edit .env and restart this service.

Restart=on-failure
RestartSec=15s
TimeoutStopSec=15

StandardOutput=journal
StandardError=journal
SyslogIdentifier=${SERVICE_NAME}

# The dashboard is read-only — small memory footprint.
MemoryMax=256M

[Install]
WantedBy=multi-user.target
EOF

chmod 644 "${UNIT_PATH}"

echo "systemctl daemon-reload …"
systemctl daemon-reload

echo "systemctl enable ${SERVICE_NAME} (start on boot)…"
systemctl enable "${SERVICE_NAME}"

echo "systemctl start ${SERVICE_NAME} …"
systemctl start "${SERVICE_NAME}"

sleep 2

echo ""
echo "=== Status ==="
systemctl status "${SERVICE_NAME}" --no-pager -l || true

echo ""
echo "=== Done ==="
if [[ -n "${TAILSCALE_IP}" ]]; then
    echo "  Dashboard URL (Tailscale, accessible from any tailnet device):"
    echo "      http://${TAILSCALE_IP}:${DASH_PORT}/predictor_dashboard.html"
else
    echo "  Dashboard URL on this VPS:"
    echo "      http://<vps-ip>:${DASH_PORT}/predictor_dashboard.html"
    echo "  (Tailscale not detected.  If you have it: 'tailscale ip -4' shows the IP.)"
fi
echo ""
echo "  Tail logs:    sudo journalctl -u ${SERVICE_NAME} -f"
echo "  Restart:      sudo systemctl restart ${SERVICE_NAME}"
echo "  Stop:         sudo systemctl stop ${SERVICE_NAME}"
echo ""
echo "  Change settings:  edit .env (DASHBOARD_PORT/_WATCH_SEC/_DAYS), then:"
echo "                    sudo systemctl restart ${SERVICE_NAME}"